cct:convert.o convertcomment.o
	gcc -o cct convert.o convertcomment.o
convert.o:convert.c
	gcc -o convert.o -c convert.c
convertcomment.o:convertcomment.c
	gcc -o convertcomment.o -c convertcomment.c
clean:
	rm *.o cct
